[package]
name = "basic"
version = "0.1.0"
authors = ["Rui <2221870259@qq.com>"]
edition = "2018"
build = "build.rs"
links = "basic"

[dependencies.basic-lib]
path = "../basic-lib"

[build-dependencies.cargo-cmake]
path = "../../"

[lib]
name = "hello_sys"
path = "lib.rs"